### ISSUE TITLE
File upload generates message: "Refused to set unsafe header 'content-length'" in the browser

### ISSUE THREAD

**Issue by daniel-bsci** [Kinvey/angular-sdk#7]

**Comment by tejasranade** [comment]
I suspect this header is being set because Google cloud storage requires it - https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload
We'll look into whether it can be avoided.

@daniel-bsci - Does the file transfer succeed when you run into the message?
Also, please provide some additional information about the environment in which you're running this (browser type / version + Kinvey SDK version). Thanks.
